### ISSUE TITLE
Crashes when exiting game

### ISSUE THREAD

**Issue by pjlasl** [Minenash/Seamless-Loading-Screen#19]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/6/21, 11:21 AM
Description: Rendering screen

java.lang.NullPointerException: Screen cannot be null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.afterRender(ScreenEvents.java:138)
	at net.minecraft.class_757.handler$bhb000$onAfterRenderScreen(class_757.java:1978)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.afterRender(ScreenEvents.java:138)
	at net.minecraft.class_757.handler$bhb000$onAfterRenderScreen(class_757.java:1978)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_442
	Mouse location: Scaled: (474, 254). Absolute: (948.000000, 509.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 636483584 bytes (606 MB) / 3095396352 bytes (2952 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3072m
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		architectury: Architectury 1.5.105
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		better_wandering_trader: Better Wandering Trader 1.6.2
		betterend: Better End 0.8.8-beta
		biomemakeover: Biome Makeover 1.16.4-1.2.11
		blockdiversity: Block Diversity 1.1
		campanion: Campanion 1.3.2
		carpet: Carpet Mod in Fabric 1.4.24
		charm: Charm 2.2.2
		cinderscapes: Cinderscapes 1.3.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		dawn: Dawn API 1.6.2
		earlygame: EarlyGame 1.16.x-1.0.1b
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		falling_tree: FallingTree 2.10.0
		fiber: fiber 0.23.0-2
		go-fish: Go Fish 1.2.0-beta-1.16.4
		infinitevillagertrading: InfiniteVillagerTrading 1.16.5-fabric0.30.0-1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 14
		kubejs: KubeJS 1605.3.6-build.159
		lambdabettergrass: LambdaBetterGrass 1.0.3+1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		lithium: Lithium 0.6.1
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.0
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		rhino: Rhino 1.7.13-build.14
		roughlyenoughitems: Roughly Enough Items 5.9.2
		roughlyenoughitems-api: REI (API) 5.9.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.9.2
		roughlyenoughitems-runtime: REI (Runtime) 5.9.2
		seamless_loading_screen: Seamless Loading Screen 1.2.1
		smooth-chunks: Smooth Chunks 1.0.0
		spruceui: SpruceUI 2.0.4+1.16
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		traverse: Traverse 3.3.1
		tweed: Tweed API 3.0.0-beta.22
		upstream: Upstream 1.0.1
		vanilladeathchest: VanillaDeathChest 2.0.2-fabric
		verticalredstone: Vertical Redstone 1.2.0
		voyager: Voyager 1.0.0
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.8141, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, lambdabettergrass/default
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by Minenash** [comment]
That was supposed to be fixed in v1.2.0, but apparently I forgot to revert one of the files from a different attempt to fix it. It's been reverted in v1.2.2 so it should now work.
