### ISSUE TITLE
Not saving screenshots, error in log

### ISSUE THREAD

**Issue by geekywalrus** [Minenash/Seamless-Loading-Screen#37]
Screenshots are not saved by the mod on my install. **Version 1.3.4 on 1.16.5.** I get this error in my console on world exit.

`[02:02:51] [main/INFO]: [STDERR]: java.nio.file.AccessDeniedException: 
[02:02:51] [main/INFO]: [STDERR]: 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
[02:02:51] [main/INFO]: [STDERR]: 	at java.nio.file.Files.newByteChannel(Files.java:361)
[02:02:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_1011.method_4314(class_1011.java:491)
[02:02:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_1011.method_4325(class_1011.java:446)
[02:02:51] [main/INFO]: [STDERR]: 	at com.minenash.seamless_loading_screen.FinishQuit.method_25394(FinishQuit.java:80)
[02:02:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:616)
[02:02:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1048)
[02:02:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[02:02:51] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:02:51] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:02:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[02:02:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[02:02:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:02:51] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:02:51] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:02:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[02:02:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[02:02:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[02:02:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

**Comment by Dragon-Seeker** [comment]
I belive such has been dealt with during the rewrite of the mod meaning such should not happen anymore.

**Comment by spikespaz** [comment]
@Dragon-Seeker Maybe it is a not best to close all of these issues until the rewrite is completed and released?
