### ISSUE TITLE
[BUG] After getting kicked from a server, the next leave doesnt correctly  remove you from the server

### ISSUE THREAD

**Issue by 456dev** [Minenash/Seamless-Loading-Screen#47]
# Bug

## Description

when disconnecting after previously being kicked, the player doesn't correctly disconnect for the server
this causes hangs with the integrated server

### Steps

1. join a server
2. get kicked from the server
3. join (the same or another) server, or single player world
4. leave the world
5. observe how in multiplayer, the previous kick message is displayed, and the singleplayer console is spammed
6. observe how in the multiplayer console, the player is still logged in (`list`), and there is no disconnect message
7. observe how in singleplayer, the game freezes, needing to be closed externally

### client

- `fabric@0.37.1+1.17`
- `fabric-api-base@0.3.0+a02b446318`
- `fabric-api-lookup-api-v1@1.2.0+2b5c62d018`
- `fabric-biome-api-v1@3.1.11+c345aea818`
- `fabric-blockrenderlayer-v1@1.1.5+a02b446318`
- `fabric-command-api-v1@1.1.3+5ab9934c18`
- `fabric-commands-v0@0.2.2+92519afa18`
- `fabric-containers-v0@0.1.12+a02b446318`
- `fabric-content-registries-v0@0.2.2+a02b446318`
- `fabric-crash-report-info-v1@0.1.5+be9da31018`
- `fabric-dimensions-v1@2.0.11+6cefd57718`
- `fabric-entity-events-v1@1.1.0+a02b446318`
- `fabric-events-interaction-v0@0.4.9+a722d8c018`
- `fabric-events-lifecycle-v0@0.2.1+92519afa18`
- `fabric-game-rule-api-v1@1.0.7+6cefd57718`
- `fabric-item-api-v1@1.2.4+a02b446318`
- `fabric-item-groups-v0@0.2.10+b7ab612118`
- `fabric-key-binding-api-v1@1.0.4+a02b446318`
- `fabric-keybindings-v0@0.2.2+36b77c3e18`
- `fabric-lifecycle-events-v1@1.4.4+a02b446318`
- `fabric-loot-tables-v1@1.0.4+a02b446318`
- `fabric-mining-levels-v0@0.1.3+92519afa18`
- `fabric-models-v0@0.3.0+a02b446318`
- `fabric-networking-api-v1@1.0.12+6cefd57718`
- `fabric-networking-blockentity-v0@0.2.11+a02b446318`
- `fabric-networking-v0@0.3.2+92519afa18`
- `fabric-object-builder-api-v1@1.10.9+b7ab612118`
- `fabric-object-builders-v0@0.7.3+a02b446318`
- `fabric-particles-v1@0.2.4+a02b446318`
- `fabric-registry-sync-v0@0.7.10+e2961fee18`
- `fabric-renderer-api-v1@0.4.4+5f02c96918`
- `fabric-renderer-indigo@0.4.8+a02b446318`
- `fabric-renderer-registries-v1@3.2.0+a02b446318`
- `fabric-rendering-data-attachment-v1@0.1.5+a02b446318`
- `fabric-rendering-fluids-v1@0.1.13+a02b446318`
- `fabric-rendering-v0@1.1.2+92519afa18`
- `fabric-rendering-v1@1.6.0+a02b446318`
- `fabric-resource-loader-v0@0.4.8+a00e834b18`
- `fabric-screen-api-v1@1.0.4+155f865c18`
- `fabric-screen-handler-api-v1@1.1.8+a02b446318`
- `fabric-structure-api-v1@1.1.13+5ab9934c18`
- `fabric-tag-extensions-v0@1.1.4+a02b446318`
- `fabric-textures-v0@1.0.6+a02b446318`
- `fabric-tool-attribute-api-v1@1.2.12+b7ab612118`
- `fabric-transfer-api-v1@1.0.0+3fe3c3f518`
- `fabricloader@0.11.6`
- `java@16`
- `minecraft@1.17.1`
- `seamless_loading_screen@1.3.6+1.17.1`

### server

(but it should be unrelated, since it can be done in single player)

```
[18:08:46 INFO]: Checking version, please wait...
[18:08:47 INFO]: This server is running Paper version git-Paper-157 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f521a18)
You are 9 version(s) behind
```

**Comment by jimchen5209** [comment]
Same issue and after client freezing it ends up showing the kick message last time even you clicked on disconnect.

Client:
- Minecraft 1.17.1
- Fabric loader 0.11.6
- Fabric API 0.37.2
- Seamless Loading Screen 1.3.6

And client log:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8469(int)" because "this.field_3699" is null
	at net.minecraft.class_634.method_11086(class_634.java:487) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2777.method_11922(class_2777.java:49) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2777.method_11054(class_2777.java:7) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

[09:45:21] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_24367()" because "???" is null
	at net.minecraft.class_1308.<init>(class_1308.java:124) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:12) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1588.<init>(class_1588.java:30) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1642.<init>(class_1642.java:93) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:475) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1299.method_5886(class_1299.java:493) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1299.method_5889(class_1299.java:480) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_634.method_11138(class_634.java:792) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2610.method_11217(class_2610.java:85) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2610.method_11054(class_2610.java:13) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

[09:45:21] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8469(int)" because "this.field_3699" is null
	at net.minecraft.class_634.method_11093(class_634.java:457) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:39) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:11) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
Full log: [Google Drive](https://drive.google.com/file/d/1jS7a3ljdbKnHGF_UWANfzFUrWxtThxER/view)

**Comment by tort-oise** [comment]
Exactly the same issue. I thought it was AutoReconnect doing it, but I was apparently wrong. This mod seems so harmless, and it's so nice, I wish this didn't happen.

**Comment by ThatOtherAndrew** [comment]
Can confirm, I have the exact same issue.

**Comment by tort-oise** [comment]
Confirm x2, using latest version of this mod on 1.17, latest Fabric API version, and latest Fabric and Minecraft version (1.17.1).

It does this logout thing, then it zucks the game, and spams this error into the log,

`[21:09:51] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8469(int)" because "â˜ƒ" is null
	at net.minecraft.class_2726.method_11786(class_2726.java:35) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_634.method_11139(class_634.java:538) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2726.method_11788(class_2726.java:31) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2726.method_11054(class_2726.java:9) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[21:09:51] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null`

wasting log file space at an alarming rate. I had this running for around 5 minutes, and my log file became over 50 mb. Imagine if you just kept playing like nothing happened. I'm lucky I noticed it, but someone else might not, and this is a pretty mod-breaking feature.

**Comment by tort-oise** [comment]
https://paste.ee/p/bX4ly

This is only a small portion of my log file, and there's tons more. This could become very bad if it doesn't get fixed soon.

**Comment by SzczurekYT** [comment]
Also experiancing this, on 1.18.1 when I leave the server the player isn't properly removed from the server and stays on it and can drown or be killed by zombie. So with the mod you actually can't disconnect from the server. Hope for 1.18, because this is a great mod.

**Comment by tort-oise** [comment]
1.18, still not fixed. Wow.

**Comment by tort-oise** [comment]
It is.

**Comment by Dragon-Seeker** [comment]
Due to the age of this issue, I don't know if such has been fixed in the latest version but it would be great if any here would be up to test such.
