### ISSUE TITLE
Quitting the server results in an infinite blank screen loop.

### ISSUE THREAD

**Issue by MobButcher** [Minenash/Seamless-Loading-Screen#48]
When I left my singleplayer world, my screen went completely black and blank, apart from the RAM meter I have with another mod installed. While it was refreshing constantly and without any hiccups, the game itself froze in this state. Upon closing it threw me an error:

```
[00:28:45] [Server thread/INFO]: MobButcher lost connection: Disconnected
[00:28:45] [Server thread/INFO]: MobButcher left the game
[00:28:45] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
[00:28:45] [Render thread/INFO]: Stopping worker threads
[00:28:45] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[00:28:45] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[00:28:45] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1132.method_3725()" because the return value of "net.minecraft.class_310.method_1576()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.31) ~[?:?]
	at com.minenash.seamless_loading_screen.FinishQuit.render(FinishQuit.java:87) ~[seamless-loading-screen-1.3.6+1.17.1.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2209) ~[?:?]
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2185) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onDisconnected(ClientPlayNetworkHandler:712) ~[?:?]
	at com.minenash.seamless_loading_screen.FinishQuit.render(FinishQuit.java:99) ~[seamless-loading-screen-1.3.6+1.17.1.jar:?]```

Full log: https://paste.ee/p/eTptd.

Seamless Loading Screen 1.3.6;
Minecraft 1.17.1
Fabric Loader 0.11.6
Fabric API 0.37.0

**Comment by MobButcher** [comment]
Also, with this setup I have encountered #1 and #11, but it does not happen consistently.

**Comment by Dragon-Seeker** [comment]
Due to the age of this issue and the rewrite the mod took, I am closing this issue until such happens again. Please make a new issue if such dose
