### ISSUE TITLE
Incompatible with ipv6

### ISSUE THREAD

**Issue by david-buderus** [Minenash/Seamless-Loading-Screen#65]
The client crashes if you try to connect to a server with ipv6.
You are able to connect if you remove Seamless Loading Screen.

Recreate:
Try to join a local server with ::1 (ipv6 localhost).

> Description: mouseClicked event handler
>
> java.nio.file.InvalidPathException: Illegal char <:> at index 93: C:\Users\David\curseforge\minecraft\Instances\Create Flavored\screenshots/worlds/servers/2a02:908:2212:aee0:c13a:5602:2c3f:74e9_25565.png
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?] {}
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?] {}
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?] {}
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?] {}
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?] {}
	at java.nio.file.Path.of(Path.java:147) ~[?:?] {re:mixin}
	at java.nio.file.Paths.get(Paths.java:69) ~[?:?] {}
	at com.daderpduck.seamless_loading_screen.ScreenshotLoader.setScreenshot(ScreenshotLoader.java:41) ~[seamless_loading_screen-1.18-3.0.0.jar%23127!/:1.18-3.0.0] {re:classloading}
	at com.daderpduck.seamless_loading_screen.ScreenshotLoader.setScreenshotServer(ScreenshotLoader.java:32) ~[seamless_loading_screen-1.18-3.0.0.jar%23127!/:1.18-3.0.0] {re:classloading}
	at com.daderpduck.seamless_loading_screen.events.EventHandler.initGuiEvent(EventHandler.java:40) ~[seamless_loading_screen-1.18-3.0.0.jar%23127!/:1.18-3.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_271_EventHandler_initGuiEvent_InitScreenEvent.invoke(.dynamic) ~[?:?] {}
`

**Comment by Dragon-Seeker** [comment]
Should be fixed within the given rewrite of the mod, making sure to filter the IPv6 address to replace illegal characters.
