### ISSUE TITLE
[Bug] Crash on closing world when having F3 or Debug menu open

### ISSUE THREAD

**Issue by Dragon-Seeker** [Minenash/Seamless-Loading-Screen#85]
```
Stacktrace:
java.lang.IllegalStateException: Current profile not ended
	at net.minecraft.client.gl.GlTimer.beginProfile(GlTimer.java:21)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1201)
	at net.minecraft.client.MinecraftClient.reset(MinecraftClient.java:2210)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient.java:2181)
	at net.minecraft.client.gui.screen.GameMenuScreen.disconnect(GameMenuScreen.java:112)
	at net.minecraft.client.report.AbuseReportContext.tryShowDraftScreen(AbuseReportContext.java:53)
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19836(GameMenuScreen.java:95)
	at net.minecraft.client.gui.screen.GameMenuScreen.md526db1$seamless_loading_screen$lambda$adjust$1$2(GameMenuScreen.java:1018)
	at com.minenash.seamless_loading_screen.OnLeaveHelper.takeScreenShot(OnLeaveHelper.java:105)
	at net.minecraft.client.render.GameRenderer.handler$gpj000$seamless_loading_screen$attemptToTakeScreenshot(GameRenderer.java:10603)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:897)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

This is due to `GlTimer` instance begin profile being called twice before a end call leading to it crashing out, but such only happens if the F3 menu is open.

**Comment by Dragon-Seeker** [comment]
Should be fixed in a2e93bfa41637a040f83cfed9e26d50db284959c commit
